spring:
  application:
    name: milker
  datasource:
    url: jdbc:postgresql://localhost:5432/Milker
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

open:
  api:
    title: "Milker"
    version: "1.0"
    description: "API document of project Milker"
    server:
      url: "http://localhost:8080"
      description: "SpringBoot"
    group: "Milk"
    scan-package: "PRM392.demo.controller"

logging:
  level:
    org:
      hibernate: INFO
